name: content_cache
description: content_cache
version: 0.0.7
homepage: https://github.com/jWinterDay/content_cache

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # flutter:
  #   sdk: flutter

  meta: ^1.10.0
  di_visualizer_annotation: ^0.0.1

dev_dependencies:
  flutter_lints: ^3.0.1
